### ISSUE TITLE
Train custom model

### ISSUE THREAD

**Issue by alelordelo** [aartykov/Latent-Composer-pytorch#2]
Thanks for finally releasing the code:

What are the steps to train a custom model? Would be greta to have a Discord to we can exchange ideas about fine tuning Latent Composer.

thanks

**Comment by aartykov** [comment]
Hey! First you need to install and train as it is shown in the readme file. Just running the main.py file is enough to start training.

**Comment by alelordelo** [comment]
but is this possible to train with own custom dataset?

**Comment by aartykov** [comment]
Ideally, the model needs to be trained on a public dataset, like LAION and only then finetuned with a custom dataset. Since I do not have the hardware to do such large-scale training, I leave the model as it is. To train the model, you can mimic the dataset class in the /ldm/data/custom_dataset.py file.
